name: Daily Auto Commit Bot

on:
  schedule:
    - cron: "20 6 * * *"   # runs once per day
  workflow_dispatch:

jobs:
  - name: Verify GH_PAT exists
    run: |
      if [ -z "$GH_PAT" ]; then
        echo "GH_PAT is empty"
        exit 1
      else
        echo "GH_PAT is present"
        echo "Length: ${#GH_PAT}"
      fi
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run auto commit
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python scripts/auto_commit.py
